pipelines:
  default:
    - step:
        name: php
        image: composer:latest
        caches:
          - composer
        script:
          - composer --version
          - php -v
          - composer install
          - composer test